### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by pgera** [negativo17/GraphicsMagick#1]
I have the epel-multimedia repo enabled on a rhel 7 system. I'm seeing the following error:

-> Running transaction check
---> Package GraphicsMagick.x86_64 0:1.3.25-7.el7 will be updated
---> Package GraphicsMagick.x86_64 0:1.3.26-1.el7 will be an update
--> Processing Dependency: libwebp.so.4()(64bit) for package: GraphicsMagick-1.3.26-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: GraphicsMagick-1.3.26-1.el7.x86_64 (epel)
           Requires: libwebp.so.4()(64bit)
           Available: libwebp-0.3.0-3.el7.x86_64 (rhel-x86_64-server-7)
               libwebp.so.4()(64bit)
           Installed: libwebp-0.5.1-2.el7.x86_64 (@epel-multimedia)
              ~libwebp.so.6()(64bit)
 You could try using --skip-broken to work around the problem

It looks like epel's GraphicsMagick is newer, but it needs an older libwebp. Downgrading libwebp would break the following packages from epel-multimedia:

webkitgtk3-2.4.9-7.el7.x86_64 (@epel-multimedia)
GraphicsMagick-1.3.25-7.el7.x86_64 (@epel-multimedia)
1:gstreamer1-plugins-bad-1.4.5-4.el7.x86_64 (@epel-multimedia)
python-pillow-2.1.0-6.el7.x86_64 (@epel-multimedia)

**Comment by scaronni** [comment]
New update built, will be available soon (1 or 2 hours).
Thanks for reporting.

**Comment by scaronni** [comment]
Btw, just ignore the GraphicsMagick update for now.
